competition: march-machine-learning-mania-2026
target_season: 2026
regular_season_last_day: 132
men_detailed_start_season: 2003
women_detailed_start_season: 2010
raw_data_subdirectory: march-machine-learning-mania-2026
random_seed: 2026
