/* Authored synthetic teams and outcomes. No real teams, games, or model artifacts. */
globalThis.MARCH_TOURNAMENT_DATA = {
  schema_version: 1,
  evidence_type: "SYNTHETIC_ONLY",
  teams: [
    {
      id: "harbor",
      name: "Harbor Foxes",
      short: "HFX",
      seed: 1,
      rating: 1720,
      color: "#164e63",
    },
    {
      id: "copper",
      name: "Copper Owls",
      short: "COW",
      seed: 2,
      rating: 1680,
      color: "#9a3412",
    },
    {
      id: "cedar",
      name: "Cedar Comets",
      short: "CCM",
      seed: 3,
      rating: 1640,
      color: "#3730a3",
    },
    {
      id: "summit",
      name: "Summit Herons",
      short: "SHR",
      seed: 4,
      rating: 1600,
      color: "#166534",
    },
    {
      id: "juniper",
      name: "Juniper Kites",
      short: "JKT",
      seed: 5,
      rating: 1580,
      color: "#9d174d",
    },
    {
      id: "orchard",
      name: "Orchard Lynx",
      short: "OLX",
      seed: 6,
      rating: 1540,
      color: "#6b21a8",
    },
    {
      id: "mesa",
      name: "Mesa Otters",
      short: "MOT",
      seed: 7,
      rating: 1500,
      color: "#854d0e",
    },
    {
      id: "meadow",
      name: "Meadow Finches",
      short: "MFI",
      seed: 8,
      rating: 1460,
      color: "#115e59",
    },
  ],
  bracket: [
    "harbor",
    "meadow",
    "summit",
    "juniper",
    "copper",
    "mesa",
    "cedar",
    "orchard",
  ],
  scoring: {
    requests: [
      { game_id: "demo-01", team_a: "harbor", team_b: "meadow" },
      { game_id: "demo-02", team_a: "copper", team_b: "mesa" },
      { game_id: "demo-03", team_a: "cedar", team_b: "orchard" },
      { game_id: "demo-04", team_a: "summit", team_b: "juniper" },
      { game_id: "demo-05", team_a: "harbor", team_b: "copper" },
      { game_id: "demo-06", team_a: "cedar", team_b: "summit" },
      { game_id: "demo-07", team_a: "juniper", team_b: "orchard" },
      { game_id: "demo-08", team_a: "mesa", team_b: "meadow" },
      { game_id: "demo-09", team_a: "harbor", team_b: "cedar" },
      { game_id: "demo-10", team_a: "copper", team_b: "summit" },
      { game_id: "demo-11", team_a: "juniper", team_b: "mesa" },
      { game_id: "demo-12", team_a: "orchard", team_b: "meadow" },
      { game_id: "demo-13", team_a: "harbor", team_b: "juniper" },
      { game_id: "demo-14", team_a: "copper", team_b: "orchard" },
      { game_id: "demo-15", team_a: "cedar", team_b: "mesa" },
      { game_id: "demo-16", team_a: "summit", team_b: "meadow" },
    ],
    outcomes: [
      { game_id: "demo-01", winner_id: "harbor" },
      { game_id: "demo-02", winner_id: "copper" },
      { game_id: "demo-03", winner_id: "orchard" },
      { game_id: "demo-04", winner_id: "summit" },
      { game_id: "demo-05", winner_id: "copper" },
      { game_id: "demo-06", winner_id: "cedar" },
      { game_id: "demo-07", winner_id: "juniper" },
      { game_id: "demo-08", winner_id: "meadow" },
      { game_id: "demo-09", winner_id: "harbor" },
      { game_id: "demo-10", winner_id: "copper" },
      { game_id: "demo-11", winner_id: "mesa" },
      { game_id: "demo-12", winner_id: "orchard" },
      { game_id: "demo-13", winner_id: "harbor" },
      { game_id: "demo-14", winner_id: "copper" },
      { game_id: "demo-15", winner_id: "cedar" },
      { game_id: "demo-16", winner_id: "summit" },
    ],
  },
  provenance: {
    author: "Alvaro Mendizabal",
    evidence_type: "SYNTHETIC_ONLY",
    fixture_scope:
      "Eight fictional teams, illustrative ratings and sixteen authored game outcomes.",
    rating_source:
      "Manually authored illustrative numbers; not estimated from these outcomes.",
    scoring_scope:
      "Synthetic scoring sample for interactive metric inspection; not an untouched holdout.",
    official_evaluation: false,
    private_assets_used: false,
    training_fits: 0,
  },
};
